generator:
  class: sfPropelGenerator
  param:
    model_class:           kategori
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              kategori
    plural:                kategoris
    route_prefix:          kategori
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
         title: Master Kategori
      filter:
         display: [nama_kategori,keterangan]
      form:
         display:
            Form Kategori: [nama_kategori,keterangan]
      edit:
         title: Edit Kategori
      new:
         title: Add Kategori