# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Admin Panel
    description:  Admin Panel for Inventory Application
    keywords:     symfony, project
    language:     en
    robots:       index, follow

  stylesheets:    [bootstrap.min.css, main.css,font-awesome.min.css, '/admin/pages/css/tasks.css','components.css', 'plugins.css', '/admin/layout/css/layout.css', '/admin/layout/css/themes/darkblue.css', '/admin/layout/css/custom.css']

  javascripts:    [jquery-2.0.2.min.js, bootstrap.min.js, metronic.js, '/admin/layout/scripts/layout.js', '/admin/layout/scripts/quick-sidebar.js', '/admin/layout/scripts/demo.js', '/admin/pages/scripts/index.js', '/admin/pages/scripts/tasks.js']

  has_layout:     true
  layout:         layout
