<?php



/**
 * This class defines the structure of the 'detail_barang_masuk' table.
 *
 *
 * This class was autogenerated by Propel 1.7.0 on:
 *
 * 07/21/15 02:00:08
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class DetailBarangMasukTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.DetailBarangMasukTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('detail_barang_masuk');
        $this->setPhpName('DetailBarangMasuk');
        $this->setClassname('DetailBarangMasuk');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('id', 'Id', 'INTEGER', true, null, null);
        $this->addForeignKey('id_barang_masuk', 'IdBarangMasuk', 'INTEGER', 'barang_masuk', 'id', false, null, null);
        $this->addForeignKey('id_barang', 'IdBarang', 'INTEGER', 'barang', 'id', false, null, null);
        $this->addColumn('harga', 'Harga', 'INTEGER', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('BarangMasuk', 'BarangMasuk', RelationMap::MANY_TO_ONE, array('id_barang_masuk' => 'id', ), 'CASCADE', 'CASCADE');
        $this->addRelation('Barang', 'Barang', RelationMap::MANY_TO_ONE, array('id_barang' => 'id', ), 'CASCADE', 'CASCADE');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' =>  array (
  'form' => 'true',
  'filter' => 'true',
),
            'symfony_behaviors' =>  array (
),
        );
    } // getBehaviors()

} // DetailBarangMasukTableMap
