<?php


/**
 * This class defines the structure of the 'detail_transaksi' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/13/15 03:12:17
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class DetailTransaksiTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.DetailTransaksiTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('detail_transaksi');
		$this->setPhpName('DetailTransaksi');
		$this->setClassname('DetailTransaksi');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addForeignKey('ID_TRANSAKSI', 'IdTransaksi', 'INTEGER', 'transaksi', 'ID', false, 11, null);
		$this->addForeignKey('ID_BARANG', 'IdBarang', 'INTEGER', 'barang', 'ID', false, 11, null);
		$this->addColumn('JUMLAH', 'Jumlah', 'INTEGER', false, 11, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Transaksi', 'Transaksi', RelationMap::MANY_TO_ONE, array('id_transaksi' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Barang', 'Barang', RelationMap::MANY_TO_ONE, array('id_barang' => 'id', ), 'CASCADE', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // DetailTransaksiTableMap
