<?php



/**
 * This class defines the structure of the 'kota' table.
 *
 *
 * This class was autogenerated by Propel 1.7.0 on:
 *
 * 07/21/15 02:00:10
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class KotaTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.KotaTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('kota');
        $this->setPhpName('Kota');
        $this->setClassname('Kota');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('id', 'Id', 'INTEGER', true, null, null);
        $this->addColumn('nama_kota', 'NamaKota', 'VARCHAR', false, 50, null);
        $this->addForeignKey('id_propinsi', 'IdPropinsi', 'INTEGER', 'propinsi', 'id', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Propinsi', 'Propinsi', RelationMap::MANY_TO_ONE, array('id_propinsi' => 'id', ), 'CASCADE', 'CASCADE');
        $this->addRelation('Customers', 'Customers', RelationMap::ONE_TO_MANY, array('id' => 'id_kota', ), 'CASCADE', 'CASCADE', 'Customerss');
        $this->addRelation('Produsen', 'Produsen', RelationMap::ONE_TO_MANY, array('id' => 'id_kota', ), 'CASCADE', 'CASCADE', 'Produsens');
        $this->addRelation('Supplier', 'Supplier', RelationMap::ONE_TO_MANY, array('id' => 'id_kota', ), 'CASCADE', 'CASCADE', 'Suppliers');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' =>  array (
  'form' => 'true',
  'filter' => 'true',
),
            'symfony_behaviors' =>  array (
),
        );
    } // getBehaviors()

} // KotaTableMap
