<?php



/**
 * This class defines the structure of the 'propinsi' table.
 *
 *
 * This class was autogenerated by Propel 1.7.0 on:
 *
 * 07/21/15 02:00:13
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class PropinsiTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.PropinsiTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('propinsi');
        $this->setPhpName('Propinsi');
        $this->setClassname('Propinsi');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('id', 'Id', 'INTEGER', true, null, null);
        $this->addColumn('nama_propinsi', 'NamaPropinsi', 'VARCHAR', false, 50, null);
        $this->addForeignKey('id_negara', 'IdNegara', 'INTEGER', 'negara', 'id', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Negara', 'Negara', RelationMap::MANY_TO_ONE, array('id_negara' => 'id', ), 'CASCADE', 'CASCADE');
        $this->addRelation('Kota', 'Kota', RelationMap::ONE_TO_MANY, array('id' => 'id_propinsi', ), 'CASCADE', 'CASCADE', 'Kotas');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' =>  array (
  'form' => 'true',
  'filter' => 'true',
),
            'symfony_behaviors' =>  array (
),
        );
    } // getBehaviors()

} // PropinsiTableMap
