<?php


/**
 * Base class that represents a query for the 'detail_transaksi' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.0 on:
 *
 * 07/21/15 02:00:09
 *
 * @method DetailTransaksiQuery orderById($order = Criteria::ASC) Order by the id column
 * @method DetailTransaksiQuery orderByIdTransaksi($order = Criteria::ASC) Order by the id_transaksi column
 * @method DetailTransaksiQuery orderByIdBarang($order = Criteria::ASC) Order by the id_barang column
 * @method DetailTransaksiQuery orderByJumlah($order = Criteria::ASC) Order by the jumlah column
 *
 * @method DetailTransaksiQuery groupById() Group by the id column
 * @method DetailTransaksiQuery groupByIdTransaksi() Group by the id_transaksi column
 * @method DetailTransaksiQuery groupByIdBarang() Group by the id_barang column
 * @method DetailTransaksiQuery groupByJumlah() Group by the jumlah column
 *
 * @method DetailTransaksiQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method DetailTransaksiQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method DetailTransaksiQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method DetailTransaksiQuery leftJoinTransaksi($relationAlias = null) Adds a LEFT JOIN clause to the query using the Transaksi relation
 * @method DetailTransaksiQuery rightJoinTransaksi($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Transaksi relation
 * @method DetailTransaksiQuery innerJoinTransaksi($relationAlias = null) Adds a INNER JOIN clause to the query using the Transaksi relation
 *
 * @method DetailTransaksiQuery leftJoinBarang($relationAlias = null) Adds a LEFT JOIN clause to the query using the Barang relation
 * @method DetailTransaksiQuery rightJoinBarang($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Barang relation
 * @method DetailTransaksiQuery innerJoinBarang($relationAlias = null) Adds a INNER JOIN clause to the query using the Barang relation
 *
 * @method DetailTransaksi findOne(PropelPDO $con = null) Return the first DetailTransaksi matching the query
 * @method DetailTransaksi findOneOrCreate(PropelPDO $con = null) Return the first DetailTransaksi matching the query, or a new DetailTransaksi object populated from the query conditions when no match is found
 *
 * @method DetailTransaksi findOneByIdTransaksi(int $id_transaksi) Return the first DetailTransaksi filtered by the id_transaksi column
 * @method DetailTransaksi findOneByIdBarang(int $id_barang) Return the first DetailTransaksi filtered by the id_barang column
 * @method DetailTransaksi findOneByJumlah(int $jumlah) Return the first DetailTransaksi filtered by the jumlah column
 *
 * @method array findById(int $id) Return DetailTransaksi objects filtered by the id column
 * @method array findByIdTransaksi(int $id_transaksi) Return DetailTransaksi objects filtered by the id_transaksi column
 * @method array findByIdBarang(int $id_barang) Return DetailTransaksi objects filtered by the id_barang column
 * @method array findByJumlah(int $jumlah) Return DetailTransaksi objects filtered by the jumlah column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseDetailTransaksiQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseDetailTransaksiQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = null, $modelName = null, $modelAlias = null)
    {
        if (null === $dbName) {
            $dbName = 'propel';
        }
        if (null === $modelName) {
            $modelName = 'DetailTransaksi';
        }
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new DetailTransaksiQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param   DetailTransaksiQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return DetailTransaksiQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof DetailTransaksiQuery) {
            return $criteria;
        }
        $query = new DetailTransaksiQuery(null, null, $modelAlias);

        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   DetailTransaksi|DetailTransaksi[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = DetailTransaksiPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is already in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(DetailTransaksiPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Alias of findPk to use instance pooling
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 DetailTransaksi A model object, or null if the key is not found
     * @throws PropelException
     */
     public function findOneById($key, $con = null)
     {
        return $this->findPk($key, $con);
     }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 DetailTransaksi A model object, or null if the key is not found
     * @throws PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `id`, `id_transaksi`, `id_barang`, `jumlah` FROM `detail_transaksi` WHERE `id` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new DetailTransaksi();
            $obj->hydrate($row);
            DetailTransaksiPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return DetailTransaksi|DetailTransaksi[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|DetailTransaksi[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return DetailTransaksiQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(DetailTransaksiPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return DetailTransaksiQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(DetailTransaksiPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id >= 12
     * $query->filterById(array('max' => 12)); // WHERE id <= 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return DetailTransaksiQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id)) {
            $useMinMax = false;
            if (isset($id['min'])) {
                $this->addUsingAlias(DetailTransaksiPeer::ID, $id['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($id['max'])) {
                $this->addUsingAlias(DetailTransaksiPeer::ID, $id['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(DetailTransaksiPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the id_transaksi column
     *
     * Example usage:
     * <code>
     * $query->filterByIdTransaksi(1234); // WHERE id_transaksi = 1234
     * $query->filterByIdTransaksi(array(12, 34)); // WHERE id_transaksi IN (12, 34)
     * $query->filterByIdTransaksi(array('min' => 12)); // WHERE id_transaksi >= 12
     * $query->filterByIdTransaksi(array('max' => 12)); // WHERE id_transaksi <= 12
     * </code>
     *
     * @see       filterByTransaksi()
     *
     * @param     mixed $idTransaksi The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return DetailTransaksiQuery The current query, for fluid interface
     */
    public function filterByIdTransaksi($idTransaksi = null, $comparison = null)
    {
        if (is_array($idTransaksi)) {
            $useMinMax = false;
            if (isset($idTransaksi['min'])) {
                $this->addUsingAlias(DetailTransaksiPeer::ID_TRANSAKSI, $idTransaksi['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($idTransaksi['max'])) {
                $this->addUsingAlias(DetailTransaksiPeer::ID_TRANSAKSI, $idTransaksi['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(DetailTransaksiPeer::ID_TRANSAKSI, $idTransaksi, $comparison);
    }

    /**
     * Filter the query on the id_barang column
     *
     * Example usage:
     * <code>
     * $query->filterByIdBarang(1234); // WHERE id_barang = 1234
     * $query->filterByIdBarang(array(12, 34)); // WHERE id_barang IN (12, 34)
     * $query->filterByIdBarang(array('min' => 12)); // WHERE id_barang >= 12
     * $query->filterByIdBarang(array('max' => 12)); // WHERE id_barang <= 12
     * </code>
     *
     * @see       filterByBarang()
     *
     * @param     mixed $idBarang The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return DetailTransaksiQuery The current query, for fluid interface
     */
    public function filterByIdBarang($idBarang = null, $comparison = null)
    {
        if (is_array($idBarang)) {
            $useMinMax = false;
            if (isset($idBarang['min'])) {
                $this->addUsingAlias(DetailTransaksiPeer::ID_BARANG, $idBarang['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($idBarang['max'])) {
                $this->addUsingAlias(DetailTransaksiPeer::ID_BARANG, $idBarang['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(DetailTransaksiPeer::ID_BARANG, $idBarang, $comparison);
    }

    /**
     * Filter the query on the jumlah column
     *
     * Example usage:
     * <code>
     * $query->filterByJumlah(1234); // WHERE jumlah = 1234
     * $query->filterByJumlah(array(12, 34)); // WHERE jumlah IN (12, 34)
     * $query->filterByJumlah(array('min' => 12)); // WHERE jumlah >= 12
     * $query->filterByJumlah(array('max' => 12)); // WHERE jumlah <= 12
     * </code>
     *
     * @param     mixed $jumlah The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return DetailTransaksiQuery The current query, for fluid interface
     */
    public function filterByJumlah($jumlah = null, $comparison = null)
    {
        if (is_array($jumlah)) {
            $useMinMax = false;
            if (isset($jumlah['min'])) {
                $this->addUsingAlias(DetailTransaksiPeer::JUMLAH, $jumlah['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($jumlah['max'])) {
                $this->addUsingAlias(DetailTransaksiPeer::JUMLAH, $jumlah['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(DetailTransaksiPeer::JUMLAH, $jumlah, $comparison);
    }

    /**
     * Filter the query by a related Transaksi object
     *
     * @param   Transaksi|PropelObjectCollection $transaksi The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 DetailTransaksiQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByTransaksi($transaksi, $comparison = null)
    {
        if ($transaksi instanceof Transaksi) {
            return $this
                ->addUsingAlias(DetailTransaksiPeer::ID_TRANSAKSI, $transaksi->getId(), $comparison);
        } elseif ($transaksi instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(DetailTransaksiPeer::ID_TRANSAKSI, $transaksi->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByTransaksi() only accepts arguments of type Transaksi or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Transaksi relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return DetailTransaksiQuery The current query, for fluid interface
     */
    public function joinTransaksi($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Transaksi');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Transaksi');
        }

        return $this;
    }

    /**
     * Use the Transaksi relation Transaksi object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   TransaksiQuery A secondary query class using the current class as primary query
     */
    public function useTransaksiQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinTransaksi($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Transaksi', 'TransaksiQuery');
    }

    /**
     * Filter the query by a related Barang object
     *
     * @param   Barang|PropelObjectCollection $barang The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 DetailTransaksiQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByBarang($barang, $comparison = null)
    {
        if ($barang instanceof Barang) {
            return $this
                ->addUsingAlias(DetailTransaksiPeer::ID_BARANG, $barang->getId(), $comparison);
        } elseif ($barang instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(DetailTransaksiPeer::ID_BARANG, $barang->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByBarang() only accepts arguments of type Barang or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Barang relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return DetailTransaksiQuery The current query, for fluid interface
     */
    public function joinBarang($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Barang');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Barang');
        }

        return $this;
    }

    /**
     * Use the Barang relation Barang object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   BarangQuery A secondary query class using the current class as primary query
     */
    public function useBarangQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinBarang($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Barang', 'BarangQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   DetailTransaksi $detailTransaksi Object to remove from the list of results
     *
     * @return DetailTransaksiQuery The current query, for fluid interface
     */
    public function prune($detailTransaksi = null)
    {
        if ($detailTransaksi) {
            $this->addUsingAlias(DetailTransaksiPeer::ID, $detailTransaksi->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
