<?php

/**
 * Base class that represents a row from the 'barang' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/13/15 03:12:14
 *
 * @package    lib.model.om
 */
abstract class BaseBarang extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        BarangPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the nama_barang field.
	 * @var        string
	 */
	protected $nama_barang;

	/**
	 * The value for the id_kategori field.
	 * @var        int
	 */
	protected $id_kategori;

	/**
	 * The value for the stock field.
	 * @var        int
	 */
	protected $stock;

	/**
	 * The value for the id_kemasan field.
	 * @var        int
	 */
	protected $id_kemasan;

	/**
	 * The value for the id_produsen field.
	 * @var        int
	 */
	protected $id_produsen;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * The value for the id_harga field.
	 * @var        int
	 */
	protected $id_harga;

	/**
	 * @var        Kategori
	 */
	protected $aKategori;

	/**
	 * @var        Kemasan
	 */
	protected $aKemasan;

	/**
	 * @var        Produsen
	 */
	protected $aProdusen;

	/**
	 * @var        Harga
	 */
	protected $aHarga;

	/**
	 * @var        array DetailBarangMasuk[] Collection to store aggregation of DetailBarangMasuk objects.
	 */
	protected $collDetailBarangMasuks;

	/**
	 * @var        Criteria The criteria used to select the current contents of collDetailBarangMasuks.
	 */
	private $lastDetailBarangMasukCriteria = null;

	/**
	 * @var        array DetailTransaksi[] Collection to store aggregation of DetailTransaksi objects.
	 */
	protected $collDetailTransaksis;

	/**
	 * @var        Criteria The criteria used to select the current contents of collDetailTransaksis.
	 */
	private $lastDetailTransaksiCriteria = null;

	/**
	 * @var        array LinkBarangRak[] Collection to store aggregation of LinkBarangRak objects.
	 */
	protected $collLinkBarangRaks;

	/**
	 * @var        Criteria The criteria used to select the current contents of collLinkBarangRaks.
	 */
	private $lastLinkBarangRakCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'BarangPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [nama_barang] column value.
	 * 
	 * @return     string
	 */
	public function getNamaBarang()
	{
		return $this->nama_barang;
	}

	/**
	 * Get the [id_kategori] column value.
	 * 
	 * @return     int
	 */
	public function getIdKategori()
	{
		return $this->id_kategori;
	}

	/**
	 * Get the [stock] column value.
	 * 
	 * @return     int
	 */
	public function getStock()
	{
		return $this->stock;
	}

	/**
	 * Get the [id_kemasan] column value.
	 * 
	 * @return     int
	 */
	public function getIdKemasan()
	{
		return $this->id_kemasan;
	}

	/**
	 * Get the [id_produsen] column value.
	 * 
	 * @return     int
	 */
	public function getIdProdusen()
	{
		return $this->id_produsen;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Get the [id_harga] column value.
	 * 
	 * @return     int
	 */
	public function getIdHarga()
	{
		return $this->id_harga;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Barang The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = BarangPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [nama_barang] column.
	 * 
	 * @param      string $v new value
	 * @return     Barang The current object (for fluent API support)
	 */
	public function setNamaBarang($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nama_barang !== $v) {
			$this->nama_barang = $v;
			$this->modifiedColumns[] = BarangPeer::NAMA_BARANG;
		}

		return $this;
	} // setNamaBarang()

	/**
	 * Set the value of [id_kategori] column.
	 * 
	 * @param      int $v new value
	 * @return     Barang The current object (for fluent API support)
	 */
	public function setIdKategori($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_kategori !== $v) {
			$this->id_kategori = $v;
			$this->modifiedColumns[] = BarangPeer::ID_KATEGORI;
		}

		if ($this->aKategori !== null && $this->aKategori->getId() !== $v) {
			$this->aKategori = null;
		}

		return $this;
	} // setIdKategori()

	/**
	 * Set the value of [stock] column.
	 * 
	 * @param      int $v new value
	 * @return     Barang The current object (for fluent API support)
	 */
	public function setStock($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->stock !== $v) {
			$this->stock = $v;
			$this->modifiedColumns[] = BarangPeer::STOCK;
		}

		return $this;
	} // setStock()

	/**
	 * Set the value of [id_kemasan] column.
	 * 
	 * @param      int $v new value
	 * @return     Barang The current object (for fluent API support)
	 */
	public function setIdKemasan($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_kemasan !== $v) {
			$this->id_kemasan = $v;
			$this->modifiedColumns[] = BarangPeer::ID_KEMASAN;
		}

		if ($this->aKemasan !== null && $this->aKemasan->getId() !== $v) {
			$this->aKemasan = null;
		}

		return $this;
	} // setIdKemasan()

	/**
	 * Set the value of [id_produsen] column.
	 * 
	 * @param      int $v new value
	 * @return     Barang The current object (for fluent API support)
	 */
	public function setIdProdusen($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_produsen !== $v) {
			$this->id_produsen = $v;
			$this->modifiedColumns[] = BarangPeer::ID_PRODUSEN;
		}

		if ($this->aProdusen !== null && $this->aProdusen->getId() !== $v) {
			$this->aProdusen = null;
		}

		return $this;
	} // setIdProdusen()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     Barang The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = BarangPeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Set the value of [id_harga] column.
	 * 
	 * @param      int $v new value
	 * @return     Barang The current object (for fluent API support)
	 */
	public function setIdHarga($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_harga !== $v) {
			$this->id_harga = $v;
			$this->modifiedColumns[] = BarangPeer::ID_HARGA;
		}

		if ($this->aHarga !== null && $this->aHarga->getId() !== $v) {
			$this->aHarga = null;
		}

		return $this;
	} // setIdHarga()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->nama_barang = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->id_kategori = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->stock = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->id_kemasan = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->id_produsen = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->description = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->id_harga = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 8; // 8 = BarangPeer::NUM_COLUMNS - BarangPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Barang object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aKategori !== null && $this->id_kategori !== $this->aKategori->getId()) {
			$this->aKategori = null;
		}
		if ($this->aKemasan !== null && $this->id_kemasan !== $this->aKemasan->getId()) {
			$this->aKemasan = null;
		}
		if ($this->aProdusen !== null && $this->id_produsen !== $this->aProdusen->getId()) {
			$this->aProdusen = null;
		}
		if ($this->aHarga !== null && $this->id_harga !== $this->aHarga->getId()) {
			$this->aHarga = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(BarangPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = BarangPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aKategori = null;
			$this->aKemasan = null;
			$this->aProdusen = null;
			$this->aHarga = null;
			$this->collDetailBarangMasuks = null;
			$this->lastDetailBarangMasukCriteria = null;

			$this->collDetailTransaksis = null;
			$this->lastDetailTransaksiCriteria = null;

			$this->collLinkBarangRaks = null;
			$this->lastLinkBarangRakCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(BarangPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseBarang:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				BarangPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseBarang:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(BarangPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseBarang:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseBarang:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				BarangPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aKategori !== null) {
				if ($this->aKategori->isModified() || $this->aKategori->isNew()) {
					$affectedRows += $this->aKategori->save($con);
				}
				$this->setKategori($this->aKategori);
			}

			if ($this->aKemasan !== null) {
				if ($this->aKemasan->isModified() || $this->aKemasan->isNew()) {
					$affectedRows += $this->aKemasan->save($con);
				}
				$this->setKemasan($this->aKemasan);
			}

			if ($this->aProdusen !== null) {
				if ($this->aProdusen->isModified() || $this->aProdusen->isNew()) {
					$affectedRows += $this->aProdusen->save($con);
				}
				$this->setProdusen($this->aProdusen);
			}

			if ($this->aHarga !== null) {
				if ($this->aHarga->isModified() || $this->aHarga->isNew()) {
					$affectedRows += $this->aHarga->save($con);
				}
				$this->setHarga($this->aHarga);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = BarangPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = BarangPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += BarangPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collDetailBarangMasuks !== null) {
				foreach ($this->collDetailBarangMasuks as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collDetailTransaksis !== null) {
				foreach ($this->collDetailTransaksis as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collLinkBarangRaks !== null) {
				foreach ($this->collLinkBarangRaks as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aKategori !== null) {
				if (!$this->aKategori->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aKategori->getValidationFailures());
				}
			}

			if ($this->aKemasan !== null) {
				if (!$this->aKemasan->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aKemasan->getValidationFailures());
				}
			}

			if ($this->aProdusen !== null) {
				if (!$this->aProdusen->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aProdusen->getValidationFailures());
				}
			}

			if ($this->aHarga !== null) {
				if (!$this->aHarga->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aHarga->getValidationFailures());
				}
			}


			if (($retval = BarangPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collDetailBarangMasuks !== null) {
					foreach ($this->collDetailBarangMasuks as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collDetailTransaksis !== null) {
					foreach ($this->collDetailTransaksis as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collLinkBarangRaks !== null) {
					foreach ($this->collLinkBarangRaks as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = BarangPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getNamaBarang();
				break;
			case 2:
				return $this->getIdKategori();
				break;
			case 3:
				return $this->getStock();
				break;
			case 4:
				return $this->getIdKemasan();
				break;
			case 5:
				return $this->getIdProdusen();
				break;
			case 6:
				return $this->getDescription();
				break;
			case 7:
				return $this->getIdHarga();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = BarangPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getNamaBarang(),
			$keys[2] => $this->getIdKategori(),
			$keys[3] => $this->getStock(),
			$keys[4] => $this->getIdKemasan(),
			$keys[5] => $this->getIdProdusen(),
			$keys[6] => $this->getDescription(),
			$keys[7] => $this->getIdHarga(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = BarangPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setNamaBarang($value);
				break;
			case 2:
				$this->setIdKategori($value);
				break;
			case 3:
				$this->setStock($value);
				break;
			case 4:
				$this->setIdKemasan($value);
				break;
			case 5:
				$this->setIdProdusen($value);
				break;
			case 6:
				$this->setDescription($value);
				break;
			case 7:
				$this->setIdHarga($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = BarangPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNamaBarang($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setIdKategori($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setStock($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setIdKemasan($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setIdProdusen($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setDescription($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setIdHarga($arr[$keys[7]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(BarangPeer::DATABASE_NAME);

		if ($this->isColumnModified(BarangPeer::ID)) $criteria->add(BarangPeer::ID, $this->id);
		if ($this->isColumnModified(BarangPeer::NAMA_BARANG)) $criteria->add(BarangPeer::NAMA_BARANG, $this->nama_barang);
		if ($this->isColumnModified(BarangPeer::ID_KATEGORI)) $criteria->add(BarangPeer::ID_KATEGORI, $this->id_kategori);
		if ($this->isColumnModified(BarangPeer::STOCK)) $criteria->add(BarangPeer::STOCK, $this->stock);
		if ($this->isColumnModified(BarangPeer::ID_KEMASAN)) $criteria->add(BarangPeer::ID_KEMASAN, $this->id_kemasan);
		if ($this->isColumnModified(BarangPeer::ID_PRODUSEN)) $criteria->add(BarangPeer::ID_PRODUSEN, $this->id_produsen);
		if ($this->isColumnModified(BarangPeer::DESCRIPTION)) $criteria->add(BarangPeer::DESCRIPTION, $this->description);
		if ($this->isColumnModified(BarangPeer::ID_HARGA)) $criteria->add(BarangPeer::ID_HARGA, $this->id_harga);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(BarangPeer::DATABASE_NAME);

		$criteria->add(BarangPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Barang (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNamaBarang($this->nama_barang);

		$copyObj->setIdKategori($this->id_kategori);

		$copyObj->setStock($this->stock);

		$copyObj->setIdKemasan($this->id_kemasan);

		$copyObj->setIdProdusen($this->id_produsen);

		$copyObj->setDescription($this->description);

		$copyObj->setIdHarga($this->id_harga);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getDetailBarangMasuks() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addDetailBarangMasuk($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getDetailTransaksis() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addDetailTransaksi($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getLinkBarangRaks() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addLinkBarangRak($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Barang Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     BarangPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new BarangPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Kategori object.
	 *
	 * @param      Kategori $v
	 * @return     Barang The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setKategori(Kategori $v = null)
	{
		if ($v === null) {
			$this->setIdKategori(NULL);
		} else {
			$this->setIdKategori($v->getId());
		}

		$this->aKategori = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Kategori object, it will not be re-added.
		if ($v !== null) {
			$v->addBarang($this);
		}

		return $this;
	}


	/**
	 * Get the associated Kategori object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Kategori The associated Kategori object.
	 * @throws     PropelException
	 */
	public function getKategori(PropelPDO $con = null)
	{
		if ($this->aKategori === null && ($this->id_kategori !== null)) {
			$this->aKategori = KategoriPeer::retrieveByPk($this->id_kategori);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aKategori->addBarangs($this);
			 */
		}
		return $this->aKategori;
	}

	/**
	 * Declares an association between this object and a Kemasan object.
	 *
	 * @param      Kemasan $v
	 * @return     Barang The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setKemasan(Kemasan $v = null)
	{
		if ($v === null) {
			$this->setIdKemasan(NULL);
		} else {
			$this->setIdKemasan($v->getId());
		}

		$this->aKemasan = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Kemasan object, it will not be re-added.
		if ($v !== null) {
			$v->addBarang($this);
		}

		return $this;
	}


	/**
	 * Get the associated Kemasan object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Kemasan The associated Kemasan object.
	 * @throws     PropelException
	 */
	public function getKemasan(PropelPDO $con = null)
	{
		if ($this->aKemasan === null && ($this->id_kemasan !== null)) {
			$this->aKemasan = KemasanPeer::retrieveByPk($this->id_kemasan);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aKemasan->addBarangs($this);
			 */
		}
		return $this->aKemasan;
	}

	/**
	 * Declares an association between this object and a Produsen object.
	 *
	 * @param      Produsen $v
	 * @return     Barang The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setProdusen(Produsen $v = null)
	{
		if ($v === null) {
			$this->setIdProdusen(NULL);
		} else {
			$this->setIdProdusen($v->getId());
		}

		$this->aProdusen = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Produsen object, it will not be re-added.
		if ($v !== null) {
			$v->addBarang($this);
		}

		return $this;
	}


	/**
	 * Get the associated Produsen object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Produsen The associated Produsen object.
	 * @throws     PropelException
	 */
	public function getProdusen(PropelPDO $con = null)
	{
		if ($this->aProdusen === null && ($this->id_produsen !== null)) {
			$this->aProdusen = ProdusenPeer::retrieveByPk($this->id_produsen);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aProdusen->addBarangs($this);
			 */
		}
		return $this->aProdusen;
	}

	/**
	 * Declares an association between this object and a Harga object.
	 *
	 * @param      Harga $v
	 * @return     Barang The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setHarga(Harga $v = null)
	{
		if ($v === null) {
			$this->setIdHarga(NULL);
		} else {
			$this->setIdHarga($v->getId());
		}

		$this->aHarga = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Harga object, it will not be re-added.
		if ($v !== null) {
			$v->addBarang($this);
		}

		return $this;
	}


	/**
	 * Get the associated Harga object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Harga The associated Harga object.
	 * @throws     PropelException
	 */
	public function getHarga(PropelPDO $con = null)
	{
		if ($this->aHarga === null && ($this->id_harga !== null)) {
			$this->aHarga = HargaPeer::retrieveByPk($this->id_harga);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aHarga->addBarangs($this);
			 */
		}
		return $this->aHarga;
	}

	/**
	 * Clears out the collDetailBarangMasuks collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addDetailBarangMasuks()
	 */
	public function clearDetailBarangMasuks()
	{
		$this->collDetailBarangMasuks = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collDetailBarangMasuks collection (array).
	 *
	 * By default this just sets the collDetailBarangMasuks collection to an empty array (like clearcollDetailBarangMasuks());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initDetailBarangMasuks()
	{
		$this->collDetailBarangMasuks = array();
	}

	/**
	 * Gets an array of DetailBarangMasuk objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Barang has previously been saved, it will retrieve
	 * related DetailBarangMasuks from storage. If this Barang is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array DetailBarangMasuk[]
	 * @throws     PropelException
	 */
	public function getDetailBarangMasuks($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BarangPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDetailBarangMasuks === null) {
			if ($this->isNew()) {
			   $this->collDetailBarangMasuks = array();
			} else {

				$criteria->add(DetailBarangMasukPeer::ID_BARANG, $this->id);

				DetailBarangMasukPeer::addSelectColumns($criteria);
				$this->collDetailBarangMasuks = DetailBarangMasukPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(DetailBarangMasukPeer::ID_BARANG, $this->id);

				DetailBarangMasukPeer::addSelectColumns($criteria);
				if (!isset($this->lastDetailBarangMasukCriteria) || !$this->lastDetailBarangMasukCriteria->equals($criteria)) {
					$this->collDetailBarangMasuks = DetailBarangMasukPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastDetailBarangMasukCriteria = $criteria;
		return $this->collDetailBarangMasuks;
	}

	/**
	 * Returns the number of related DetailBarangMasuk objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related DetailBarangMasuk objects.
	 * @throws     PropelException
	 */
	public function countDetailBarangMasuks(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BarangPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collDetailBarangMasuks === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(DetailBarangMasukPeer::ID_BARANG, $this->id);

				$count = DetailBarangMasukPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(DetailBarangMasukPeer::ID_BARANG, $this->id);

				if (!isset($this->lastDetailBarangMasukCriteria) || !$this->lastDetailBarangMasukCriteria->equals($criteria)) {
					$count = DetailBarangMasukPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collDetailBarangMasuks);
				}
			} else {
				$count = count($this->collDetailBarangMasuks);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a DetailBarangMasuk object to this object
	 * through the DetailBarangMasuk foreign key attribute.
	 *
	 * @param      DetailBarangMasuk $l DetailBarangMasuk
	 * @return     void
	 * @throws     PropelException
	 */
	public function addDetailBarangMasuk(DetailBarangMasuk $l)
	{
		if ($this->collDetailBarangMasuks === null) {
			$this->initDetailBarangMasuks();
		}
		if (!in_array($l, $this->collDetailBarangMasuks, true)) { // only add it if the **same** object is not already associated
			array_push($this->collDetailBarangMasuks, $l);
			$l->setBarang($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Barang is new, it will return
	 * an empty collection; or if this Barang has previously
	 * been saved, it will retrieve related DetailBarangMasuks from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Barang.
	 */
	public function getDetailBarangMasuksJoinBarangMasuk($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BarangPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDetailBarangMasuks === null) {
			if ($this->isNew()) {
				$this->collDetailBarangMasuks = array();
			} else {

				$criteria->add(DetailBarangMasukPeer::ID_BARANG, $this->id);

				$this->collDetailBarangMasuks = DetailBarangMasukPeer::doSelectJoinBarangMasuk($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(DetailBarangMasukPeer::ID_BARANG, $this->id);

			if (!isset($this->lastDetailBarangMasukCriteria) || !$this->lastDetailBarangMasukCriteria->equals($criteria)) {
				$this->collDetailBarangMasuks = DetailBarangMasukPeer::doSelectJoinBarangMasuk($criteria, $con, $join_behavior);
			}
		}
		$this->lastDetailBarangMasukCriteria = $criteria;

		return $this->collDetailBarangMasuks;
	}

	/**
	 * Clears out the collDetailTransaksis collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addDetailTransaksis()
	 */
	public function clearDetailTransaksis()
	{
		$this->collDetailTransaksis = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collDetailTransaksis collection (array).
	 *
	 * By default this just sets the collDetailTransaksis collection to an empty array (like clearcollDetailTransaksis());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initDetailTransaksis()
	{
		$this->collDetailTransaksis = array();
	}

	/**
	 * Gets an array of DetailTransaksi objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Barang has previously been saved, it will retrieve
	 * related DetailTransaksis from storage. If this Barang is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array DetailTransaksi[]
	 * @throws     PropelException
	 */
	public function getDetailTransaksis($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BarangPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDetailTransaksis === null) {
			if ($this->isNew()) {
			   $this->collDetailTransaksis = array();
			} else {

				$criteria->add(DetailTransaksiPeer::ID_BARANG, $this->id);

				DetailTransaksiPeer::addSelectColumns($criteria);
				$this->collDetailTransaksis = DetailTransaksiPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(DetailTransaksiPeer::ID_BARANG, $this->id);

				DetailTransaksiPeer::addSelectColumns($criteria);
				if (!isset($this->lastDetailTransaksiCriteria) || !$this->lastDetailTransaksiCriteria->equals($criteria)) {
					$this->collDetailTransaksis = DetailTransaksiPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastDetailTransaksiCriteria = $criteria;
		return $this->collDetailTransaksis;
	}

	/**
	 * Returns the number of related DetailTransaksi objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related DetailTransaksi objects.
	 * @throws     PropelException
	 */
	public function countDetailTransaksis(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BarangPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collDetailTransaksis === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(DetailTransaksiPeer::ID_BARANG, $this->id);

				$count = DetailTransaksiPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(DetailTransaksiPeer::ID_BARANG, $this->id);

				if (!isset($this->lastDetailTransaksiCriteria) || !$this->lastDetailTransaksiCriteria->equals($criteria)) {
					$count = DetailTransaksiPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collDetailTransaksis);
				}
			} else {
				$count = count($this->collDetailTransaksis);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a DetailTransaksi object to this object
	 * through the DetailTransaksi foreign key attribute.
	 *
	 * @param      DetailTransaksi $l DetailTransaksi
	 * @return     void
	 * @throws     PropelException
	 */
	public function addDetailTransaksi(DetailTransaksi $l)
	{
		if ($this->collDetailTransaksis === null) {
			$this->initDetailTransaksis();
		}
		if (!in_array($l, $this->collDetailTransaksis, true)) { // only add it if the **same** object is not already associated
			array_push($this->collDetailTransaksis, $l);
			$l->setBarang($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Barang is new, it will return
	 * an empty collection; or if this Barang has previously
	 * been saved, it will retrieve related DetailTransaksis from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Barang.
	 */
	public function getDetailTransaksisJoinTransaksi($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BarangPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDetailTransaksis === null) {
			if ($this->isNew()) {
				$this->collDetailTransaksis = array();
			} else {

				$criteria->add(DetailTransaksiPeer::ID_BARANG, $this->id);

				$this->collDetailTransaksis = DetailTransaksiPeer::doSelectJoinTransaksi($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(DetailTransaksiPeer::ID_BARANG, $this->id);

			if (!isset($this->lastDetailTransaksiCriteria) || !$this->lastDetailTransaksiCriteria->equals($criteria)) {
				$this->collDetailTransaksis = DetailTransaksiPeer::doSelectJoinTransaksi($criteria, $con, $join_behavior);
			}
		}
		$this->lastDetailTransaksiCriteria = $criteria;

		return $this->collDetailTransaksis;
	}

	/**
	 * Clears out the collLinkBarangRaks collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addLinkBarangRaks()
	 */
	public function clearLinkBarangRaks()
	{
		$this->collLinkBarangRaks = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collLinkBarangRaks collection (array).
	 *
	 * By default this just sets the collLinkBarangRaks collection to an empty array (like clearcollLinkBarangRaks());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initLinkBarangRaks()
	{
		$this->collLinkBarangRaks = array();
	}

	/**
	 * Gets an array of LinkBarangRak objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Barang has previously been saved, it will retrieve
	 * related LinkBarangRaks from storage. If this Barang is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array LinkBarangRak[]
	 * @throws     PropelException
	 */
	public function getLinkBarangRaks($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BarangPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collLinkBarangRaks === null) {
			if ($this->isNew()) {
			   $this->collLinkBarangRaks = array();
			} else {

				$criteria->add(LinkBarangRakPeer::ID_BARANG, $this->id);

				LinkBarangRakPeer::addSelectColumns($criteria);
				$this->collLinkBarangRaks = LinkBarangRakPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(LinkBarangRakPeer::ID_BARANG, $this->id);

				LinkBarangRakPeer::addSelectColumns($criteria);
				if (!isset($this->lastLinkBarangRakCriteria) || !$this->lastLinkBarangRakCriteria->equals($criteria)) {
					$this->collLinkBarangRaks = LinkBarangRakPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastLinkBarangRakCriteria = $criteria;
		return $this->collLinkBarangRaks;
	}

	/**
	 * Returns the number of related LinkBarangRak objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related LinkBarangRak objects.
	 * @throws     PropelException
	 */
	public function countLinkBarangRaks(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BarangPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collLinkBarangRaks === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(LinkBarangRakPeer::ID_BARANG, $this->id);

				$count = LinkBarangRakPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(LinkBarangRakPeer::ID_BARANG, $this->id);

				if (!isset($this->lastLinkBarangRakCriteria) || !$this->lastLinkBarangRakCriteria->equals($criteria)) {
					$count = LinkBarangRakPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collLinkBarangRaks);
				}
			} else {
				$count = count($this->collLinkBarangRaks);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a LinkBarangRak object to this object
	 * through the LinkBarangRak foreign key attribute.
	 *
	 * @param      LinkBarangRak $l LinkBarangRak
	 * @return     void
	 * @throws     PropelException
	 */
	public function addLinkBarangRak(LinkBarangRak $l)
	{
		if ($this->collLinkBarangRaks === null) {
			$this->initLinkBarangRaks();
		}
		if (!in_array($l, $this->collLinkBarangRaks, true)) { // only add it if the **same** object is not already associated
			array_push($this->collLinkBarangRaks, $l);
			$l->setBarang($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Barang is new, it will return
	 * an empty collection; or if this Barang has previously
	 * been saved, it will retrieve related LinkBarangRaks from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Barang.
	 */
	public function getLinkBarangRaksJoinRak($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BarangPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collLinkBarangRaks === null) {
			if ($this->isNew()) {
				$this->collLinkBarangRaks = array();
			} else {

				$criteria->add(LinkBarangRakPeer::ID_BARANG, $this->id);

				$this->collLinkBarangRaks = LinkBarangRakPeer::doSelectJoinRak($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(LinkBarangRakPeer::ID_BARANG, $this->id);

			if (!isset($this->lastLinkBarangRakCriteria) || !$this->lastLinkBarangRakCriteria->equals($criteria)) {
				$this->collLinkBarangRaks = LinkBarangRakPeer::doSelectJoinRak($criteria, $con, $join_behavior);
			}
		}
		$this->lastLinkBarangRakCriteria = $criteria;

		return $this->collLinkBarangRaks;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collDetailBarangMasuks) {
				foreach ((array) $this->collDetailBarangMasuks as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collDetailTransaksis) {
				foreach ((array) $this->collDetailTransaksis as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collLinkBarangRaks) {
				foreach ((array) $this->collLinkBarangRaks as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collDetailBarangMasuks = null;
		$this->collDetailTransaksis = null;
		$this->collLinkBarangRaks = null;
			$this->aKategori = null;
			$this->aKemasan = null;
			$this->aProdusen = null;
			$this->aHarga = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseBarang:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseBarang::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseBarang
