<?php


/**
 * Base class that represents a query for the 'negara' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.0 on:
 *
 * 07/21/15 02:00:12
 *
 * @method NegaraQuery orderById($order = Criteria::ASC) Order by the id column
 * @method NegaraQuery orderByNamaNegara($order = Criteria::ASC) Order by the nama_negara column
 *
 * @method NegaraQuery groupById() Group by the id column
 * @method NegaraQuery groupByNamaNegara() Group by the nama_negara column
 *
 * @method NegaraQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method NegaraQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method NegaraQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method NegaraQuery leftJoinPropinsi($relationAlias = null) Adds a LEFT JOIN clause to the query using the Propinsi relation
 * @method NegaraQuery rightJoinPropinsi($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Propinsi relation
 * @method NegaraQuery innerJoinPropinsi($relationAlias = null) Adds a INNER JOIN clause to the query using the Propinsi relation
 *
 * @method Negara findOne(PropelPDO $con = null) Return the first Negara matching the query
 * @method Negara findOneOrCreate(PropelPDO $con = null) Return the first Negara matching the query, or a new Negara object populated from the query conditions when no match is found
 *
 * @method Negara findOneByNamaNegara(string $nama_negara) Return the first Negara filtered by the nama_negara column
 *
 * @method array findById(int $id) Return Negara objects filtered by the id column
 * @method array findByNamaNegara(string $nama_negara) Return Negara objects filtered by the nama_negara column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseNegaraQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseNegaraQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = null, $modelName = null, $modelAlias = null)
    {
        if (null === $dbName) {
            $dbName = 'propel';
        }
        if (null === $modelName) {
            $modelName = 'Negara';
        }
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new NegaraQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param   NegaraQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return NegaraQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof NegaraQuery) {
            return $criteria;
        }
        $query = new NegaraQuery(null, null, $modelAlias);

        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Negara|Negara[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = NegaraPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is already in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(NegaraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Alias of findPk to use instance pooling
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 Negara A model object, or null if the key is not found
     * @throws PropelException
     */
     public function findOneById($key, $con = null)
     {
        return $this->findPk($key, $con);
     }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return                 Negara A model object, or null if the key is not found
     * @throws PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `id`, `nama_negara` FROM `negara` WHERE `id` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Negara();
            $obj->hydrate($row);
            NegaraPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Negara|Negara[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Negara[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return NegaraQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(NegaraPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return NegaraQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(NegaraPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id >= 12
     * $query->filterById(array('max' => 12)); // WHERE id <= 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return NegaraQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id)) {
            $useMinMax = false;
            if (isset($id['min'])) {
                $this->addUsingAlias(NegaraPeer::ID, $id['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($id['max'])) {
                $this->addUsingAlias(NegaraPeer::ID, $id['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(NegaraPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the nama_negara column
     *
     * Example usage:
     * <code>
     * $query->filterByNamaNegara('fooValue');   // WHERE nama_negara = 'fooValue'
     * $query->filterByNamaNegara('%fooValue%'); // WHERE nama_negara LIKE '%fooValue%'
     * </code>
     *
     * @param     string $namaNegara The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return NegaraQuery The current query, for fluid interface
     */
    public function filterByNamaNegara($namaNegara = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($namaNegara)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $namaNegara)) {
                $namaNegara = str_replace('*', '%', $namaNegara);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(NegaraPeer::NAMA_NEGARA, $namaNegara, $comparison);
    }

    /**
     * Filter the query by a related Propinsi object
     *
     * @param   Propinsi|PropelObjectCollection $propinsi  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return                 NegaraQuery The current query, for fluid interface
     * @throws PropelException - if the provided filter is invalid.
     */
    public function filterByPropinsi($propinsi, $comparison = null)
    {
        if ($propinsi instanceof Propinsi) {
            return $this
                ->addUsingAlias(NegaraPeer::ID, $propinsi->getIdNegara(), $comparison);
        } elseif ($propinsi instanceof PropelObjectCollection) {
            return $this
                ->usePropinsiQuery()
                ->filterByPrimaryKeys($propinsi->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterByPropinsi() only accepts arguments of type Propinsi or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Propinsi relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return NegaraQuery The current query, for fluid interface
     */
    public function joinPropinsi($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Propinsi');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Propinsi');
        }

        return $this;
    }

    /**
     * Use the Propinsi relation Propinsi object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   PropinsiQuery A secondary query class using the current class as primary query
     */
    public function usePropinsiQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinPropinsi($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Propinsi', 'PropinsiQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   Negara $negara Object to remove from the list of results
     *
     * @return NegaraQuery The current query, for fluid interface
     */
    public function prune($negara = null)
    {
        if ($negara) {
            $this->addUsingAlias(NegaraPeer::ID, $negara->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
