generator:
  class: sfPropelGenerator
  param:
    model_class:           barang
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              barang
    plural:                barangs
    route_prefix:          barang
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
         title: Master Barang
      filter:
         display: [nama_barang,id_kategori,id_kemasan,id_produsen]
      form:
         display:
            Form Barang: [nama_barang,id_kategori,id_kemasan,id_produsen,stock,description]
      edit:
         title: Edit Barang
      new:
         title: Add Barang
