generator:
  class: sfPropelGenerator
  param:
    model_class:           harga
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              harga
    plural:                hargas
    route_prefix:          harga
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
         title: Master Harga
      filter:
         display: [nominal,kurs,description,id_barang]
      form:
         display:
            Form Harga: [nominal,kurs,description,id_barang,active]
      edit:
         title: Edit Harga
      new:
         title: Add Harga
