generator:
  class: sfPropelGenerator
  param:
    model_class:           kemasan
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              kemasan
    plural:                kemasans
    route_prefix:          kemasan
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
         title: Master Kemasan
      filter:
         display: [nama_kemasan,description]
      form:
         display:
            Form Kemasan: [nama_kemasan,description]
      edit:
         title: Edit Kemasan
      new:
         title: Add Kemasan
