<?php



/**
 * Skeleton subclass for performing query and update operations on the 'log_barang' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.0 on:
 *
 * 07/21/15 01:45:26
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class LogBarangQuery extends BaseLogBarangQuery
{
}
