generator:
  class: sfPropelGenerator
  param:
    model_class:           produsen
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              produsen
    plural:                produsens
    route_prefix:          produsen
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
         title: Master Produsen
      filter:
         display: [nama_produsen,alamat,id_kota,telp]
      form:
         display:
            Form Produsen: [nama_produsen,alamat,id_kota,telp]
      edit:
         title: Edit Produsen
      new:
         title: Add Produsen